# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='movie',
  syntax='proto3',
  serialized_options=b'Z\007.;movie',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmovie.proto\x12\x05movie\"1\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\t\"\x14\n\x06Search\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x37\n\x0cMovieService\x12\'\n\x08GetMovie\x12\r.movie.Search\x1a\x0c.movie.MovieB\tZ\x07.;movieb\x06proto3'
)




_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='movie.Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='movie.Movie.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='movie.Movie.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='movie.Movie.rating', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)


_SEARCH = _descriptor.Descriptor(
  name='Search',
  full_name='movie.Search',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='movie.Search.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.message_types_by_name['Search'] = _SEARCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), {
  'DESCRIPTOR' : _MOVIE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.Movie)
  })
_sym_db.RegisterMessage(Movie)

Search = _reflection.GeneratedProtocolMessageType('Search', (_message.Message,), {
  'DESCRIPTOR' : _SEARCH,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.Search)
  })
_sym_db.RegisterMessage(Search)


DESCRIPTOR._options = None

_MOVIESERVICE = _descriptor.ServiceDescriptor(
  name='MovieService',
  full_name='movie.MovieService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMovie',
    full_name='movie.MovieService.GetMovie',
    index=0,
    containing_service=None,
    input_type=_SEARCH,
    output_type=_MOVIE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVIESERVICE)

DESCRIPTOR.services_by_name['MovieService'] = _MOVIESERVICE

# @@protoc_insertion_point(module_scope)
